[package]
name = "youtube"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
reqwest = { version = "0.12", features = ["blocking", "gzip"] }
simd-json = "0.13.10"
